### ISSUE TITLE
About haystack: is it possible to patch the individual APKs instead of the framework JARs?

### ISSUE THREAD

**Issue by ccaapton** [DexPatcher/dexpatcher-tool#20]
Hi Lanchon. I roughly understand that haystack is [patching](https://gist.github.com/Lanchon/78854e97dc8f1d2a6b11a0a134d06c6c)  the "PackageParser" class(the callee) in the framework JAR. But it is very painful to modify the framework:
1. users need root the phone
2. the ROM need to be deodexed
3. different android version need be patched differently

Looks like dexpatcher 1.5 have implemented "cross-class editing". I'm not entirely sure what that is,  but could this [patch](https://gist.github.com/Lanchon/78854e97dc8f1d2a6b11a0a134d06c6c) been applied to the individual APK(the caller) that use "PackageParser", utilizing this cross-class editing? If possible, then users can patch the apks on their computers(or in an android app), self-sign the package, and use MicroG on un-rooted phones.

This trick could also be used by app-developers against untrusted close-sourced third-party SDKs. Many SDKs call privileged api and do nasty things, but the app-developer can not change the framework api. If cross-class edit is possible to be used in this way, the app-developer could intercept sensitive calls and protect themselves as well as their users.

**Comment by Lanchon** [comment]
1) because free software OSes exists, nobody should ever use no free OSes. what is the point of microG if you have a full OS that you don't have the source for? haystack should not exist; you should build your OS from scratch.

2) so you plan to mod each and EVERY APP (and update) that uses google APIs?!! that is plain crazy.

3) dexpatcher was created to patch apps, not frameworks. see the docs.

4) but dexpatcher changes code, not code invocations. there is a plan to extend it in that direction, but still xposed would be better for that use case. what about own signature change? patch the get-signature API invocations? what about dynamically invoked get-signature calls... patch all usage of the reflection API to mod the invoke on get-signature? what about reading own apk file... patch all usage of file I/O to mod APK-self reading? what about dynamically loaded code... patch all usage of class loaders to patch dex bytecode before loading with all these changes... by including a copy of dexpatcher itself in the app and invoke it during class loading? what about reading own apk file, etc using native code... got you here right?

5) there is the plan for a dexpatcher-live, that applies dex changes stored elsewhere in the system to apks on-demand during apk byecode compilation and without the apks themselves being modified. this would be akin to xposed with some advantages (much easier to code patches, much better error checking on patch application, more versatile mods possible, mod would be sandboxed with app and not root so you dont need to trust the modder that much, no reboot to change mods, no security holes or loss of performance associated with xposed, ability to automatically adapt patches to newer app versions even in the face of obfuscation (by using queries to locate code items according to bytecode invariants across obfuscation, etc)) and some disadvantages (cannot patch framework: many times it is odexed and i will not deodex on install (like xposed does; too much work), and in principle any change to any part of the framework would require a reboot and complete recompilation of the whole framework (which is not reasonable for patch development)). my view: dexpatcher-live would be better to patch apps, and xposed would be better to patch frameworks.

**Comment by ccaapton** [comment]
I got your idea about the self-verification. Indeed patching external code is the better choice. Thanks a lot!
