### ISSUE TITLE
EmptyMultiDexContainerException while patching multidex application

### ISSUE THREAD

**Issue by Unbrick** [DexPatcher/dexpatcher-tool#31]
Hey Lanchon,

i'm struggling a little bit using your command line tool:

Tool version: 1.8.0-alpha4
Setup: Patching a ProGuard obfuscated APK with a non-compiled patch (.java files)
Command: `java -jar dexpatcher-1.8.0-alpha4.jar -m -v -o patched.apk ./source.apk patched-app/`
Output:
```
DexPatcher version 1.8.0-alpha4 by Lanchon (https://dexpatcher.github.io/)
info: read './source.apk'
info: read 'patched-app'
fatal: exception: lanchon.multidexlib2.EmptyMultiDexContainerException: patched-app/
```

The patched-app folder is a standard gradle folder structure, first level contents are:

```
drwxr-xr-x 6 root root 4096 Feb 20 17:16 app
-rw-r--r-- 1 root root 2378 Feb 20 15:43 build.gradle
drwxr-xr-x 3 root root 4096 Feb 20 12:44 gradle
-rw-r--r-- 1 root root  786 Feb 20 16:23 gradle.properties
-rwxr-xr-x 1 root root 5305 Feb 20 12:44 gradlew
-rw-r--r-- 1 root root 2269 Feb 20 12:44 gradlew.bat
-rw-r--r-- 1 root root  330 Feb 20 12:44 local.properties
-rw-r--r-- 1 root root  865 Feb 20 12:48 patched-app.iml
-rw-r--r-- 1 root root   15 Feb 20 12:44 settings.gradle
```

DexPatcher does not seem to recognize that the patch is in the folder, tried several different paths (including app, app/src, ...). Am i doing anything wrong? Is dexpatcher capable of processing the patch this was?

Thank you in advance!

**Comment by Lanchon** [comment]
dexpatcher tool operates on dalvik bytecode. source patch and output are dex files or multidex containers. you need to compile the patch to java bytecode and then jar-to-dex it before you can feed it to dexpatcher. the patch compilation step may require importing symbols from the source apk, which entails extracting the dex bytecode, translate it to java bytecode, and add it as a compile-only dependency.

> EmptyMultiDexContainerException: patched-app/

means the patched-app/ dir is expected to be a multidex container and contain classesN.dex files but it doesnt.

dexpatcher-gradle is a project that provides gradle plugins to automate these kinds of workflows. it might suit your needs.

**Comment by Unbrick** [comment]
Thank you very much for your quick answer! dexpatcher-gradle unfortunatley does not work with the given ~~ProGuard~~DexGuard obfuscation due to [a bug in apktool](https://github.com/DexPatcher/dexpatcher-gradle/issues/26). 

I'll try compiling it first, thank you for the good answer!

**Comment by Lanchon** [comment]
i see.

there is a dexpatcher-gradle sample called 'patched-dex' from the dark ages on which you might want to base your effort.

btw, you can still use apktool by disabling resource processing.

apktool can pack and unpack the apk, and there are gradle tasks for apktool available in the base plugin of dxp-gradle (the one used by the sample to which i referred you.)

**Comment by Unbrick** [comment]
So in theory I could extract solely the Dex file and patch only it. Sounds pretty good but how do the ressource IDs behave in that process? Do they stay the same or do they get regenerated or break?

**Comment by Lanchon** [comment]
you dont process resources. (you cant bc apktool fails.) so what is your question exactly? (resource IDs can never be changed in an APK (only added). resources themselves can be changed.)

**Comment by Unbrick** [comment]
Oh okay I was not sure if in the process of recompiling the APK with dexpatcher the ressource IDs were generated new. But it sounds pretty much line they don't ^^

**Comment by Lanchon** [comment]
> with dexpatcher the ressource IDs were generated new

this cannot be done. no tools that do this can be created. during normal APK builds, some java source files are generated, one being the famous R class that embeds static final ints with the values of the resource IDs. this class is then compiled with the rest of the java code. references to static final ints are and MUST be inlined in the referencing class (see the JLS). this means that instead of a reference to R.string.hello you get the int VALUE of the resource ID embedded in code. javac does this. once this is done, you cannot change IDs. there is no way of knowing if an int constant in code is a resource ID or some random int.

dxp-gradle modifies the android build flow to retain the IDs of the existing resources, while letting you add new resources that will be automatically ID'd, as usual. it wil also generate a new R class (different package) combining the IDs of imported and new resources.

in your case none of this will happen. resources will remain the same. the only caveat is, your patch code will likely want to reference some existing resources. you can do this by referencing the existing R class (be it obfuscated or not) from the patch.

the problem of referencing symbols from the patch can be solved in two ways: either the patch declares all that is needed and DexIgnores it (in the future DexCheck should be used for this), or the original app code is back-translated to java bytecode for the only purpose of importing the symbols into the compilation step. the 'patch-dex' sample does the latter.

if you wanted not to import symbols and wanted to declare everything in the patch instead, the R class should be handled as follows:

declare only the resources IDs that the patch code actually needs, but make those names `static int`s instead of `static final int`s and don't set any value for them, and DexIgnore the containing class(es). this way, javac will encode a reference to the fields instead of an embedded int value (because they are not final) in the patch code. then the ID containing classes will be discarded during patching. at runtime, the references will resolve to the original R class, and the ID values will be resolved correctly. JIT/AOT compile should make the references as fast as embedded ints.

**Comment by Unbrick** [comment]
Okay no concerns about the ressource IDs anymore. Luckily currently i dont need to access the ressources at all and in case i need to add some ressources i'm thinking of dynamically inflating them!

Would be awsome if [our project](https://github.com/JodelRaccoons/JodelPatched) could work again, DexPatcher is still the best approach to do stuff like this! I'll try to figure out how the patched-dex works and report back tomorrow!

**Comment by Lanchon** [comment]
would you be able to manually fix the offending resource?

**Comment by Lanchon** [comment]
what i mean is: if you decode the app with apktool, would you be able to manually modify the produced resource files so that apktool can rebuild a working apk?

**Comment by Unbrick** [comment]
> what i mean is: if you decode the app with apktool, would you be able to manually modify the produced resource files so that apktool can rebuild a working apk?

I'm not even entirely sure what is broken there so i'm not sure ^^

Just now i tried compiling the application with the patched-dex, the compilation was also successful but the application crashes. Seems like a @DexEdit on a field did not affect all references to it, somehow theres something broken ^^

Additionally i noticed while repacking the APK file, the SHA-256 sum in the MANIFEST.MF was not updated, updating it manually did work out though.

**Comment by Lanchon** [comment]
> Seems like a @DexEdit on a field did not affect all references to it, somehow theres something broken

java is broken lol, there not much editing fields can do. one reasonable use is to increase visibility.

editing fields requires the most knowledge of java/dalvik bytecode and compiler behavior. there are in-depth test case in the test file showing the intricacies.

you are editing a field. what are the original and edited signatures? what do you want to achieve? without complete info i can't be of help.
